apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Basic_Survey
  title: Basic Survey
  description: Basic Survey
  tags:
  - recommended
  - ansible
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
  - title: Provide information about the new component
    required:
    - seed_network_route
    properties:
      seed_network_route:
        title: Route information
        description: Route information
        type: string
        maxLength: 128
        minLength: 0
  steps:
  - id: ansible
    name: Generating the Ansible Source Code Component
    action: ansible:rhaap:sync
    input:
      repoOwner: ${{ parameters.repoOwner }}
      repoName: ${{ parameters.repoName }}
      description: ${{ parameters.description }}
      collectionGroup: ${{ parameters.collectionGroup }}
      collectionName: ${{ parameters.collectionName }}
      applicationType: collection-project
      sourceControl: ${{ parameters.sourceControl }}
